# Generated by Django 6.0.1 on 2026-01-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacja_samochodow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='CarBrand',
        ),
    ]
