# Generated by Django 6.0.1 on 2026-01-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacja_samochodow', '0002_alter_car_brand_delete_carbrand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=50),
        ),
    ]
