# Generated by Django 6.0.1 on 2026-01-30 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacja_samochodow', '0003_alter_car_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='Car_TYPES',
            new_name='car_types',
        ),
    ]
